title: WCSNG Docs
description: Documentation and tutorials courtesy of ucsdwcsng
theme: just-the-docs

# baseurl: "/wcsng_docs"
url: https://ucsdwcsng.github.io

aux_links:
  "WCSNG Home":
    - "https://wcsng.ucsd.edu"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


logo: "/assets/images/wcsng_white.png"
favicon_ico: "/assets/images/favicon.ico"

color_scheme: dark